FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
ENV GOPROXY=https://goproxy.cn,direct
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o worker ./cmd/worker/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/worker .
COPY .env .
CMD ["./worker"]